hashicorp/nomad-pack-community-registry

- packs/wordpress/README.md
- packs/wordpress/metadata.hcl
- packs/wordpress/templates/_helpers.tpl
- packs/wordpress/templates/wordpress.nomad.tpl
- packs/wordpress/variables.hcl
Hello!
This pack contains a service job that runs [WordPress](https://wordpress.org/) in a single Nomad client. It currently supports
being run by the [Docker](https://www.nomadproject.io/docs/drivers/docker) driver.
It has 3 tasks:
- **WordPress:** [*(reference)*](https://wordpress.org/) the open-source CMS;
- **MariaDB:** [*(reference)*](https://mariadb.org/) the database used by Wordpress;
- **phpMyAdmin:** [*(reference)*](https://www.phpmyadmin.net/) to handle the administration of MariaDB over web.
Setup:
- Service-to-service communication is handled with Consul Connect (via sidecar proxies);
- MariaDB's state is persisted with Nomad Host Volumes;
- Consul service registration and service health checks are enabled by default for WordPress and phpMyAdmin. MariaDB only has service …
> Pack: WordPress

- packs/faasd/README.md
- packs/faasd/metadata.hcl
- packs/faasd/outputs.tpl
- packs/faasd/templates/_helpers.tpl
- packs/faasd/templates/faasd.nomad.tpl
- packs/faasd/variables.hcl
- packs/faasd/vars.nomad
This pack is for deploying Faasd (from Alex Ellis, [openfaas.com](https://www.openfaas.com/)) on Nomad.
It allows to deploy it with Consul registration or not. There is a `vars.nomad` file example that shows that you can also set dns server(s) for correct name resolving.
Let me know if you can see something to fix. It would be really appreciated!
> Add Faasd pack

- packs/influxdb/README.md
- packs/influxdb/metadata.hcl
- packs/influxdb/outputs.tpl
- packs/influxdb/templates/_helpers.tpl
- packs/influxdb/templates/influxdb.nomad.tpl
- packs/influxdb/variables.hcl
- packs/influxdb/vars.nomad
This is a PR that adds InfluxDB pack. The Nomad driver used is Docker and it allows you to pass env vars to the container to make an automated init setup of the DB. Plus, you can customize the job.
> add InfluxDB pack

- packs/outline/README.md
- packs/outline/metadata.hcl
- packs/outline/templates/_helpers.tpl
- packs/outline/templates/outline.nomad.tpl
- packs/outline/variables.hcl
Hello again!
This pack contains a service job that runs [Outline](https://www.getoutline.com/) in a single Nomad client. It currently supports
being run by the [Docker](https://www.nomadproject.io/docs/drivers/docker) driver.
It has 4 tasks:
- **Outline:** [*(reference)*](https://www.getoutline.com/) the wiki and knowledgebase for teams;
- **PostgreSQL:** [*(reference)*](https://www.postgresql.org/) the persistent database used by Outline;
- **Redis:** [*(reference)*](https://redis.io/) for in-memory storage and cache;
- **MinIO:** [*(reference)*](https://min.io/) for images storage, compatible with S3 cloud storage service.
Setup:
- Service-to-service communication is handled with Consul Connect;
- Bitnami images are being used for …
> Pack: Outline

- packs/aws_efs_csi/README.md
- packs/aws_efs_csi/metadata.hcl
- packs/aws_efs_csi/outputs.tpl
- packs/aws_efs_csi/templates/aws-efs-csi-nodes.nomad.tpl
- packs/aws_efs_csi/variables.hcl
Here is a pack to setup the AWS EFS CSI plugin running as a system job.
The job will only run on Nomad hosts with Docker privileged mode enabled and will need an IAM policy to allow the use 
of the EFS API. The plugin runs in monolith mode so that new volumes can be created dynamically.
> Pack: AWS EFS CSI plugin

- packs/rabbitmq/README.md
- packs/rabbitmq/metadata.hcl
- packs/rabbitmq/outputs.tpl
- packs/rabbitmq/templates/_consulservices.tpl
- packs/rabbitmq/templates/_helpers.tpl
- packs/rabbitmq/templates/_pki.tpl
- packs/rabbitmq/templates/_rabbitenv.tpl
- packs/rabbitmq/templates/rabbit.nomad.tpl
- packs/rabbitmq/variables.hcl
This pack is based on my old blog post of [deploying a TLS enabled RabbitMQ cluster to Nomad](https://andydote.co.uk/2019/04/06/nomad-rabbitmq-secure/).  There are some changes in how the configuration is done due to how old that post is - I'll be updating it in the near future too.
This has been tested on a 3 node vagrant based Nomad cluster.
Requirements:
- Consul: I've not sure how I can specify this requires Consul, but all Nomad clusters I have used have it available.
- Vault: Optional, but strongly preferred.
> rabbitmq: add tls cluster pack

- packs/hashicups/README.md
- packs/hashicups/metadata.hcl
- packs/hashicups/outputs.tpl
- packs/hashicups/templates/hashicups.nomad.tpl
- packs/hashicups/variables.hcl
A pack for the HashiCups demo application that deploys the app without the need for Consul (services run on static ports).
Requirements: 
- Nomad cluster (dev cluster works fine) with Docker installed
- Ability to access the Nomad client on the `nginx_port` defined in the variables file
> Pack: HashiCups

- packs/vector/README.md
- packs/vector/metadata.hcl
- packs/vector/templates/_helpers.tpl
- packs/vector/templates/vector.nomad.tpl
- packs/vector/variables.hcl
Hello!
This pack contains a single system job that runs [Vector](https://vector.dev) across all Nomad clients. It currently supports
being run by the [Docker](https://www.nomadproject.io/docs/drivers/docker) driver.
The inbuilt configuration file is configured to read from 3 sources:
- **Docker logs:** [*(reference)*](https://vector.dev/docs/reference/configuration/sources/docker_logs/) plugs into the Docker socket to collect container logs;
- **Host metrics:** [*(reference)*](https://vector.dev/docs/reference/configuration/sources/host_metrics/) collects host metrics, such as CPU, memory, disk, and network utilization with Vector's inbuilt collector;
- **Nomad metrics:** [*(reference)*](https://www.nomadproject.io/docs/operations/metrics) collects exposed Nomad metrics via the Prometheus …
> Pack: vector

- packs/grafana/CHANGELOG.md
- packs/grafana/README.md
- packs/grafana/metadata.hcl
- packs/grafana/templates/grafana.nomad.tpl
- packs/grafana/variables.hcl
- Breaking Change: all Variables related to Grafana are prefixed with `grafana_`
- added `grafana_volume` for persistent data
- added `grafana_task_artifacts` for custom Artifacts in Grafana
- added `grafana_task_config_dashboards`, `grafana_task_config_datasources` and `grafana_task_config_plugins` for automatic Grafana setup
> grafana: Update to version 0.1.0

- packs/redis/CHANGELOG.md
- packs/redis/README.md
- packs/redis/metadata.hcl
- packs/redis/outputs.tpl
- packs/redis/templates/_helpers.tpl
- packs/redis/templates/redis.conf.tpl
- packs/redis/templates/redis.nomad.tpl
- packs/redis/variables.hcl
This is an attempt to fulfill issue #36 for a Redis pack. The intent is to initially create a standalone, vanilla instance that works for small deployments. I would plan to create a separate pack for Redis in a replication/clustered setup.
A couple things I noticed that I thought might be cool to see while working with nomad-pack (unless I missed them somewhere):
- Is it possible to have variable interpolation in the `variables.hcl` file? For instance, it'd be nice to be able to reference a configured variable within another when specifying, say, the default value
- I added a redis.conf file as a template in hopes that I could render it using variables in `variables.hcl`, and add it as a template within the job spec. Is this possible? I think this would help the user update the …
> Pack: Redis

- packs/grafana/variables.hcl
tempo uses `3200` as default port
tempo/variables.hcl
```
variable "http_port" {
description = "The Nomad client port that routes to the tempo."
type        = number
default     = 3200
}
```
> fix inconsistent temp port

- packs/grafana/templates/grafana.nomad.tpl
`grafana.dns.source` does not match with `variables.hcl` as follows
```
variable "dns" {
description = ""
type = object({
servers   = list(string)
searches = list(string)
options = list(string)
})
}
```
> fix grafana dns servers in template

- .github/scripts/files-to-identifiers.sh
- .github/scripts/version-from-identifier.sh
- .github/workflows/notify-integration-release.yml
Introduces workflows for notifying the [HashiCorp Developer](https://developer.hashicorp.com/) integrations library whenever there is an update to a Pack.
Nomad does not have an integrations library on HashiCorp Developer yet  (e.x. [Waypoint's](https://developer.hashicorp.com/waypoint/integrations)), but soon will, which will include the Packs inside of this registry.
> Adds workflows for HashiCorp Developer integrations library

- .github/workflows/notify-integration-release.yml
The re-echoing of the output coerced the results to a single line, which prevented each integration update from being read in.
> Fix a bug which prevented multi-integration syncs

- packs/ceph/CHANGELOG.md
- packs/ceph/README.md
- packs/ceph/config/bad.json
- packs/ceph/config/ceph.conf
- packs/ceph/config/good.json
- packs/ceph/config/stdout.log
- packs/ceph/metadata.hcl
- packs/ceph/outputs.tpl
- packs/ceph/templates/_config.tpl
- packs/ceph/templates/_constraints.tpl
- packs/ceph/templates/_location.tpl
- packs/ceph/templates/_resources.tpl
- packs/ceph/templates/ceph.nomad.tpl
- packs/ceph/variables.hcl
- packs/ceph_rbd_csi/CHANGELOG.md
- packs/ceph_rbd_csi/README.md
- packs/ceph_rbd_csi/metadata.hcl
- packs/ceph_rbd_csi/outputs.tpl
- packs/ceph_rbd_csi/templates/_constraints.tpl
- packs/ceph_rbd_csi/templates/_location.tpl
- packs/ceph_rbd_csi/templates/_resources.tpl
- packs/ceph_rbd_csi/templates/controller.nomad.tpl
- packs/ceph_rbd_csi/templates/node.nomad.tpl
- packs/ceph_rbd_csi/variables.hcl
A pack for deploying the Ceph RBD CSI plugin and a Ceph demo
Example runs in my Vagrant cluster environment:
<details><summary>render ceph output</summary>
```
$ nomad-pack render ceph
ceph/ceph.nomad:
job "ceph" {
namespace   = "default"
region      = "global"
datacenters = ["dc1"]
group "ceph" {
constraint {
attribute = "${attr.kernel.name}"
value     = "linux"
}
constraint {
attribute = "${attr.driver.docker.privileged.enabled}"
value     = true
}
network {
#
mode = "host"
}
service {
name = "ceph-mon"
port = 3300
}
service {
name = "ceph-dashboard"
port = 5000
check {
type           = "http"
interval       = "5s"
timeout        = "1s"
path           = "/"
initial_status = "warning"
}
}
task "ceph" {
driver = "docker"
config {
image        = "ceph/daemon:latest-octopus"
args         = …
```
> Ceph RBD CSI plugin

- packs/ctfd/README.md
- packs/ctfd/metadata.hcl
- packs/ctfd/outputs.tpl
- packs/ctfd/templates/_helpers.tpl
- packs/ctfd/templates/ctfd.nomad.tpl
- packs/ctfd/variables.hcl
Here's a pack to run [**CTFd**](https://ctfd.io/) and host [CTF competitions](https://ctftime.org/ctf-wtf/) or, more generally, Cyber Security training events. It is derived from a private setup that has been battle-tested in a regional public CTF event not long ago.
+ **Drivers and requirements:** Docker driver, access to Docker volumes, existing r/w volumes, Consul.
+ **What's included:** CTFd, MariaDB, Redis; preconfigured as much as possible and including health checks and appropriate inter-dependency hooks.
+ **What's not included:** a reverse proxy for SSL termination in front of CTFd. A generic template would need to be radically altered for each setup and it's trivial to add manually when not already present elsewhere in the stack.
This pack lets operators spin up an event-ready …
> Pack: CTFd

- packs/traefik/README.md
No parens around links when using this link format.
> docs: fix links in traefik readme

- packs/democratic_csi_nfs/CHANGELOG.md
- packs/democratic_csi_nfs/README.md
- packs/democratic_csi_nfs/metadata.hcl
- packs/democratic_csi_nfs/outputs.tpl
- packs/democratic_csi_nfs/templates/_constraints.tpl
- packs/democratic_csi_nfs/templates/_location.tpl
- packs/democratic_csi_nfs/templates/_plugin_config_file.tpl
- packs/democratic_csi_nfs/templates/_resources.tpl
- packs/democratic_csi_nfs/templates/controller.nomad.tpl
- packs/democratic_csi_nfs/templates/node.nomad.tpl
- packs/democratic_csi_nfs/variables.hcl
A pack for deploying `democratic-csi` CSI plugins in their NFS client mode. I've left a few questions too.
Example runs in my Vagrant environment:
<details><summary>plan output</summary>
```
$ nomad-pack plan \
-var nfs_share_host=192.168.56.69 \
-var nfs_share_base_path=/var/nfs/general \
-var nfs_controller_mount_path=/srv/nfs_data \
./packs/democratic_csi_nfs
+ Job: "democratic_csi_controller"
+ Task Group: "controller" (2 create)
+ Task: "plugin" (forces create)
» Scheduler dry-run:
- All tasks successfully allocated.
+ Job: "democratic_csi_node"
+ Task Group: "node" (3 create)
+ Task: "plugin" (forces create)
» Scheduler dry-run:
- All tasks successfully allocated.
Plan succeeded
```
</details>
<details><summary>run output</summary>
```
$ nomad-pack run \
-var …
```
> democratic-csi plugin

- packs/tfe_fdo_nomad/CHANGELOG.md
- packs/tfe_fdo_nomad/README.md
- packs/tfe_fdo_nomad/metadata.hcl
- packs/tfe_fdo_nomad/templates/tfe.agent.nomad.tpl
- packs/tfe_fdo_nomad/templates/tfe.nomad.tpl
- packs/tfe_fdo_nomad/variables.hcl
- Updated TFE version to use GA release version.
- Using Nomad Task API instead of Nomad Job API.
- Nomad certs are no longer required.
- TFE Agent job ID now configurable.
Please confirm the following if submitting a new pack:
> TFE FDO on Nomad GA release

- .github/workflows/validate-packs.yml
- ci/validate.sh
- packs/boundary/.ci/vars-required.hcl
- packs/csi_openstack_cinder/.ci/vars-required.hcl
- packs/democratic_csi_nfs/.ci/vars-required.hcl
- packs/tfc_agent/.ci/vars-required.hcl
- packs/tfe_fdo_nomad/.ci/vars-required.hcl
Adds automatic validation for packs on PR.
This does not make sure that they actually really truly work!  But that they can:
*  `nomad-pack render` for template syntax, optionally with variables (which are sometimes required)
* `nomad fmt` for HCL syntax
* `nomad validate` for some semantic jobspec stuff
The workflow only targets changed packs, but the whole repo passes with
```
ls packs/ | while read p; do
./ci/validate.sh packs/$p || break
done
```
> CI validation
